import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeAreaViewContainer: {
    flex: 1,
    // display: 'flex',
    backgroundColor: 'white',
  },
  appTitleContainer: {
    // height: 45,
    // marginBottom: 5,
    padding: 10,
    fontSize: 20,
    fontWeight: '350',
    color: 'white',
    backgroundColor: 'black',
    textAlign: 'center',
  },
  viewTotalContainer: {
    flex: 1,
    margin: 10,
  },
  viewColumnContainer: {
    // width: "100%",
    // flex: 1,
    // margin: 10,
    flexDirection: 'column',
    // alignItems: "center",
    justifyContent: 'flex-start',
  },
  viewRowContainer: {
    // flex: 1,
    marginBottom: 10,
    flexDirection: 'row',
    // alignItems: "center",
    justifyContent: 'space-between',
  },
  textCon: {
    height: 40,
    marginBottom: 5,
    fontSize: 16,
    color: 'black',
    borderRadius: 5,
    backgroundColor: 'white',
    paddingVertical: 8,
    paddingHorizontal: 5,
  },
  labelCon: {
    height: 40,
    marginBottom: 5,
    fontSize: 16,
    color: 'black',
    borderRadius: 5,
    backgroundColor: 'lightgray',
    paddingVertical: 8,
    paddingHorizontal: 5,
  },
  textWrapCon: {
    // height: 40,
    flexShrink: 1, // 추가
    marginBottom: 5,
    fontSize: 16,
    color: 'black',
    borderColor: 'lightgray',
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: 'white',
    paddingVertical: 8,
    paddingHorizontal: 5,
  },
  textInputCon: {
    height: 40,
    marginBottom: 5,
    fontSize: 16,
    color: 'black',
    // borderRadius: 5,
    // borderColor: "gray",
    borderWidth: 0,
  },
  buttonCon: {
    height: 40,
    // marginBottom: 10,
    // marginBottom: 0,
    // paddingVertical: 7,
    // paddingHorizontal: 15,
    borderRadius: 5,
    // elevation: 3,
    // backgroundColor: 'dodgerblue',
    fontWeight: '350',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonTextCon: {
    // alignSelf: 'center',
    // lineHeight: 18,
    // letterSpacing: 0.25,
    fontSize: 16,
    // paddingHorizontal: 10,
    // paddingVertical: 5,
    // fontWeight: "500",
    color: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomButtonContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    padding: 10,
    backgroundColor: 'transparent',
  },
  tooltipCon: {
    backgroundColor: 'black',
    // alignSelf: 'center',
    // lineHeight: 18,
    // letterSpacing: 0.25,
    // fontSize: 24,
    // paddingHorizontal: 10,
    // paddingVertical: 5,
    // fontWeight: "500",
    borderRadius: 20,
    color: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconCon: {
    backgroundColor: 'black',
    // alignSelf: 'center',
    // lineHeight: 18,
    // letterSpacing: 0.25,
    fontSize: 24,
    // paddingHorizontal: 10,
    // paddingVertical: 5,
    // fontWeight: "500",
    color: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  renderSeparator: {
    backgroundColor: '#e0e0e0',
    height: 1,
  },
  // 여기서 부터는 쓰레기 백업
  viewContainer: {
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cbxInput1: {
    width: '100%',
    marginTop: 10,
    marginBottom: 10,
    height: 40,
    borderWidth: 1,
    borderColor: 'gray',
    borderRadius: 4,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  cbxInput: {
    width: '100%',
    marginTop: 10,
    marginBottom: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    height: 40,
    borderRadius: 4,
    borderColor: 'gray',
    borderWidth: 1,
  },
  txtInput: {
    width: '100%',
    marginTop: 10,
    marginBottom: 0,
    paddingHorizontal: 10,
    height: 40,
    borderRadius: 4,
    borderColor: 'gray',
    borderWidth: 1,
  },
  button: {
    width: '100%',
    height: 40,
    marginTop: 10,
    alignItems: 'center', // 가로 가운데 정렬
    justifyContent: 'center', // 세로 가운데 정렬
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 10,
    elevation: 3,
    backgroundColor: 'lightblue',
  },
  buttonText: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '500',
    letterSpacing: 0.25,
    color: 'black',
  },
  itemContainer: {
    // display: "flex",
    flex: 1,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  itemName: {
    flex: 1,
    fontSize: 16,
  },
  buttonGroup: {
    // flex: 1,
    flexDirection: 'row',
    width: 100,
    justifyContent: 'space-between',
  },
  dropDownContClose: {
    borderRadius: 25,
    width: 150,
    height: 35,
    backgroundColor: '#FFF',
  },
  dropDownContOpen: {
    borderRadius: 25,
    borderBottomStartRadius: 0,
    borderBottomEndRadius: 0,
    width: 150,
    height: 35,
    backgroundColor: '#FFF',
  },
  arrowIconStyle: { width: 20, height: 20, marginBottom: 15 },
  dropDownStyle: {
    borderRadius: 25,
    borderWidth: 0,
    backgroundColor: 'transparent',
    height: 22,
  },
  dropDownContainerStyle: {
    borderWidth: 0,
    marginTop: -14,
    borderBottomStartRadius: 25,
    borderBottomEndRadius: 25,

    color: 'gray',
    borderColor: 'gray',
  },
});
export default styles;
